version: '3'

services:
  traefik:
    image: "traefik:v2.3.3"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.dashboard=true"
      - "--api.insecure=true" # To secure the api comment this out.
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.ssh-gitlab.address=:2224"
    stop_grace_period: 30s
    networks:
      default:
        aliases:
          - "jenkins.local.net"
          - "sonarqube.local.net"
          - "gitlab.local.net"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_SERVER_NAME}`)"
      - "traefik.http.routers.dashboard.service=api@internal"
    ports:
      - "80:80"
  jenkins.local.net:
    build: .
    container_name: jenkins
    image: jenkins-libscan-tools:1.0.0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.router1.rule=Host(`$JENKINS_SERVER_NAME`)"
      - "traefik.http.routers.router1.entrypoints=web"
      - "traefik.http.routers.router1.service=jenkins"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8083"
    environment:
      - JENKINS_SLAVE_AGENT_PORT=50000
      - JENKINS_OPTS="--httpPort=8083"
      - JENKINS_ADMIN_USER=$JENKINS_ADMIN_USER
      - JENKINS_ADMIN_PASSWORD=$JENKINS_ADMIN_PASSWORD
      - CASC_JENKINS_CONFIG=$CASC_JENKINS_CONFIG
    volumes:
      - jenkins_data:/var/jenkins_home
volumes:
  jenkins_data: {}
