name: dotnet package

on:
  workflow_dispatch:
  push:
env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '3.1.x' ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Build
        working-directory: example-projects/eShopOnWeb
        run: dotnet build eShopOnWeb.sln

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/dotnet@master
        run: npx snyk test --severity-threshold=high --file=example-projects/eShopOnWeb/eShopOnWeb.sln
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        #with:
        #  args: --file=example-projects/eShopOnWeb/eShopOnWeb.sln
        

